# Generated by Django 4.2.2 on 2023-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronicity', models.CharField(choices=[('Acute', 'Acute'), ('Acute on chronic', 'Acute on chronic'), ('Chronic use', 'Chronic use')], max_length=20)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_unit', models.CharField(choices=[('year', 'year(s)'), ('month', 'month(s)')], max_length=5)),
                ('age_category', models.CharField(choices=[('Infants', 'Infants (1 month to 1 year)'), ('Children', 'Children (1 year through 12 years)'), ('Adolescents', 'Adolescents (13 years through 17 years)'), ('Adults', 'Adults (18 - 65 years)'), ('Elderly', 'Elderly > 65')], max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Pregnant', 'Pregnant'), ('Unknown', 'Unknown')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(choices=[('ng', 'ng'), ('mcg', 'mcg'), ('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('oz', 'oz'), ('IU', 'IU')], max_length=5)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dose_unit', models.CharField(choices=[('ng', 'ng'), ('mcg', 'mcg'), ('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('oz', 'oz'), ('IU', 'IU')], max_length=5)),
                ('concentration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mdd_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mdd_dose_unit', models.CharField(choices=[('ng', 'ng'), ('mcg', 'mcg'), ('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('oz', 'oz'), ('IU', 'IU')], max_length=5)),
                ('salicylate_type', models.CharField(blank=True, choices=[('Acetaminosalol', 'Acetaminosalol'), ('Aloxiprin', 'Aloxiprin'), ('Aluminum aspirin', 'Aluminum aspirin')], max_length=50, null=True)),
                ('apap_serum_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apap_serum_level_unit', models.CharField(blank=True, choices=[('mcg/dL', 'mcg/dL'), ('mg/L', 'mg/L')], max_length=10, null=True)),
                ('apap_serum_level_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apap_serum_level_time_unit', models.CharField(blank=True, choices=[('h', 'h'), ('unknown', 'unknown')], max_length=10, null=True)),
            ],
        ),
    ]
